name: Push to Public Repo

on:
  push:
    branches:
      - test-one

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Public Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Password
          git config --global user.email "git@actions.com"
          # User name
          git config --global user.name "Git"
 
          # Clone the public repository
          git clone https://github.com/bbalaji13/html-games.git public-repo
          cd public-repo

          # Create and switch to the target branch
          git checkout -b test-one || git checkout test-one

          # Use rsync to copy contents from private repository
          rsync -av --exclude='.git' ../. .

          # Commit and push changes
          git add .
          git commit -m "Update from private repository"
          git push origin test-one
