name: Push to Public Repository

on:
  push:
    branches:
      - test-one

jobs:
  push_to_public:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"
          git remote add public-repo https://github.com/bbalaji13/html-games.git
          git fetch public-repo

      - name: Check if branch2 exists
        run: |
          if git ls-remote --heads public-repo branch2 | grep -q 'refs/heads/branch2'; then
            git checkout test-one
          else
            git checkout -b test-one
          fi

      - name: Push to Public Repository
        run: |
          git push public-repo HEAD:test-one --force

env:
  PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
