name: Sync Repos

on:
  push:
    branches:
      - test-one

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v3
        with:
          ref: test-one
          repository: balaji-tynybay/HTML-games
          path: HTML-game

      - name: Checkout Private Repository
        uses: actions/checkout@v3
        with:
          ref: test-one
          repository: bbalaji13/html-games
          token: ${{ secrets.GH_PAT }} # Use the correct secret name

      - name: Copy files using rsync
        run: |
          rsync -a HTML-games/ .

      - name: Commit and Push Changes
        run: |
          git add -A
          git commit -m "Sync changes from private repo"
          git push origin test-one
