name: Push to Public Repo

on:
  push:
    branches:
      - test-one

jobs:
  push_to_public_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v3
        with:
          repository: balaji-tynybay/HTML-games
          ref: test-one

      - name: Push Changes to Public Repo
        run: |
          git remote add html-games https://github.com/bbalaji13/html-games.git
          git fetch html-games
          git checkout -b test-one
          git push html-games HEAD:test-one
