name: Sync Repos

on:
  push:
    branches:
      - test

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v2
        with:
          ref: test-one
          repository: balaji-tynybay/HTML-games
          path: HTML-game

      - name: Checkout Private Repository
        uses: actions/checkout@v2
        with:
          ref: test-one
          repository: bbalaji13/html-games
          token: ${{ secrets.GH_PAT }}
          path: my-tools

      - name: Sync Files
        run: |
          rsync -a HTML-game/ my-tools/

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Sync changes from private repo"
          git push origin test-one
