name: Sync Private Repo to Public Repo

on:
  push:
    branches:
      - test-one

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          repository: balaji-tynybay/HTML-games
          ref: test-one
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Copy files using rsync
        run: |
          rsync -a HTML-games/ .

      - name: Commit and Push Changes
        run: |
          git add -A
          git commit -m "Sync changes from private repo"
          git push origin test-one
