name: Push to Public Repo

on:
  push:
    branches:
      - test-one

permissions:
  contents: write

jobs:
  push_to_public_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v3
        with:
          repository: balaji-tynybay/HTML-games
          ref: test-one
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your@email.com"

      - name: Push Changes to Public Repo
        run: |
          git remote add html-games https://github.com/bbalaji13/html-games.git
          git fetch html-games
          git checkout -b test-one-merge-branch # Create a temporary branch in target repo
          git push html-games HEAD:test-one-merge-branch
          git checkout test-one-merge-branch
          git rm -r . # Remove all files in temporary branch
          cp -r $GITHUB_WORKSPACE/* ./ # Copy files from source repo to temporary branch
          git add .
          git commit -m "Merge changes from test-one branch"
          git push html-games HEAD:test-one-merge-branch # Push changes to the temporary branch
          git checkout main
          git branch -D test-one-merge-branch # Delete temporary branch
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

