- name: Checkout
  uses: actions/checkout@v3
  with:
    ref: test-one
    repository: balaji-tynybay/HTML-games
    path: HTML-game

- name: Checkout private tools
  uses: actions/checkout@v3
  with:
    ref: test-one
    repository: bbalaji13/html-games
    token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
    path: my-tools
      run: |
          rsync -a ../HTML-games/ .
  
- name: Commit and Push Changes
  run: |
    git add -A
    git commit -m "Sync changes from private repo"
    git push origin test-one
