name: Push to Public Repo

on:
  push:
    branches:
      - test-one

jobs:
  push_to_public_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: balaji-tynybay/HTML-games
          ref: test-one

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your@email.com"

      - name: Create New Branch in Public Repo
        run: |
          git remote add html-games https://github.com/bbalaji13/html-games.git
          git fetch html-games
          git checkout -b test-one-source-branch # Creating a new branch with a different name
          git push html-games HEAD:test-one-source-branch
          git checkout main # Switch back to the main branch
          
      - name: Copy Changes to New Branch
        run: |
          git checkout test-one-source-branch # Switch to the source branch
          cp -r $GITHUB_WORKSPACE/* ./  # Copy files to the root of the repository
          git add .
          git commit -m "Copy changes from source repository"
          git push html-games HEAD:test-one-source-branch
          
      - name: Merge Changes into Main Branch
        run: |
          git checkout main
          git merge test-one-source-branch
          git push html-games HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
