name: Push to Public Repository

on:
  push:
    branches:
      - test-one  # Adjust this to the branch you want to trigger the action on

jobs:
  push_to_public:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Public Repository
        run: |
          # Clone the public repository
          git clone https://github.com/bbalaji13/html-games.git public-repo
          
          # Navigate into the cloned repository
          cd public-repo

          # Checkout test-one
          git checkout -b test-one

          # Copy code from the private repo to the public repo
          cp -r ../. ./

          # Add, commit, and push changes
          git add .
          git commit -m "Update from private repository"
          git push origin test-one

        env:
          PAT_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
