name: Push to Public Repo

on:
  push:
    branches:
      - test-one

jobs:
  push_to_public_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your@email.com"

      - name: Merge Repo A changes into Repo B
        run: |
          git remote add repo_b https://github.com/bbalaji13/html-games.git
          git fetch repo_b
          git checkout -b test-one repo_b/test-one
          git merge origin/test-one
          git push repo_b HEAD:test-one
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
