name: Push to Public Repo

on:
  push:
    branches:
      - test-one

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Public Repo
        run: |
          # Clone the public repository
          git clone https://github.com/bbalaji13/html-games.git 
          cd html-games

          # Create and switch to the target branch
          git checkout -b test-one || git checkout test-one

          # Copy contents from private repository
          cp -r ../. .

          # Commit and push changes
          git add .
          git commit -m "Update from private repository"
          git push origin test-one
