name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy level0
        run: cd level0 && terraform init && terraform apply -auto-approve 

      - name: Deploy level1
        run: cd level1 && terraform init && terraform apply -auto-approve

      - name: Deploy level2
        run: cd level2 && terraform init && terraform apply -auto-approve
