name: Deploy to Public Repo

on:
  push:
    branches:
      - test-one

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test-one # The branch you want to deploy

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add private SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Prepare and push to public repo
        run: |
          git remote add public-repo git@github.com:bbalaji13/html-games.git
          git push public-repo test-one
        env:
          PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
