name: Sync Repos

on:
  push:
    branches:
      - test-one

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v3
        with:
          ref: test-one
          repository: balaji-tynybay/HTML-games
          path: HTML-game

      - name: Checkout Private Repository
        uses: actions/checkout@v3
        with:
          ref: test-one
          repository: bbalaji13/html-games
          token: ${{ secrets.GH_PAT }} # Use the correct secret name
          path: html-games
          steps:
          run: |
            rsync -a ../HTML-game/* .
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "Sync changes from private repo"
            git push origin test-one
