name: Push to Public Repo

on:
  push:
    branches:
      - test-one

jobs:
  push_to_public_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: balaji-tynybay/HTML-games
          ref: test-one
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout Target Repo
        run: git clone https://github.com/bbalaji13/html-games.git repo_b
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Copy Files
        run: cp -r $GITHUB_WORKSPACE/* repo_b/
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Set up Git in Target Repo
        run: |
          cd repo_b
          git config user.name "Your Name"
          git config user.email "your@email.com"

      - name: Commit and Push to Target Repo
        run: |
          cd repo_b
          git checkout -b test-one
          git add .
          git commit -m "Merge changes from test-one branch"
          git push origin test-one
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
