name: Push to Public Repo

on:
  push:
    branches:
      - test-one

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test-one # The branch you want to deploy

      - name: Push code to public repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git remote add public-repo https://github.com/bbalaji13/html-games.git
          git push --force public-repo HEAD:test-one
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
